# MCP server package: single queue, RAG + Confluence task types, enqueue, orchestrate.

from .task_queue import (
    RAG_QUERY,
    RAG_SEARCH,
    RAG_OVERVIEW,
    RAG_INDEX,
    CONFLUENCE_INTELLIGENT_ANALYZE,
    CONFLUENCE_INTELLIGENT_MATCH,
    CONFLUENCE_INTELLIGENT_FORMAT,
    CONFLUENCE_INTELLIGENT_CREATE,
    RAG_TASK_TYPES,
    CONFLUENCE_TASK_TYPES,
    ALL_TASK_TYPES,
    MCPTask,
    FailureType,
    enqueue,
    dequeue,
    re_enqueue,
    max_retries,
    is_empty,
)
from .orchestrator import (
    orchestrate,
    set_progress_callback,
    set_cancel_check,
    LIFECYCLE_QUEUED,
    LIFECYCLE_PROCESSING,
    LIFECYCLE_SUCCESS,
    LIFECYCLE_FAILURE,
    LIFECYCLE_LEARNING,
)
from . import confluence_tasks

__all__ = [
    "RAG_QUERY",
    "RAG_SEARCH",
    "RAG_OVERVIEW",
    "RAG_INDEX",
    "CONFLUENCE_INTELLIGENT_ANALYZE",
    "CONFLUENCE_INTELLIGENT_MATCH",
    "CONFLUENCE_INTELLIGENT_FORMAT",
    "CONFLUENCE_INTELLIGENT_CREATE",
    "RAG_TASK_TYPES",
    "CONFLUENCE_TASK_TYPES",
    "ALL_TASK_TYPES",
    "MCPTask",
    "FailureType",
    "enqueue",
    "dequeue",
    "re_enqueue",
    "max_retries",
    "is_empty",
    "orchestrate",
    "set_progress_callback",
    "set_cancel_check",
    "LIFECYCLE_QUEUED",
    "LIFECYCLE_PROCESSING",
    "LIFECYCLE_SUCCESS",
    "LIFECYCLE_FAILURE",
    "LIFECYCLE_LEARNING",
    "confluence_tasks",
]
